<?php
/**
 * SemestresApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apogee API
 *
 * API for apogee
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nassima.ziani1996@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * SemestresApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SemestresApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addSemestre
     *
     * adds a Semestre
     *
     * @param  string $diplome diplome (required)
     * @param  string $accro_m accro_m (required)
     * @param  string $accro_p accro_p (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\SemestreBody[]
     */
    public function addSemestre($diplome, $accro_m, $accro_p, $semestre = null)
    {
        list($response) = $this->addSemestreWithHttpInfo($diplome, $accro_m, $accro_p, $semestre);
        return $response;
    }

    /**
     * Operation addSemestreWithHttpInfo
     *
     * adds a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\SemestreBody[], HTTP status code, HTTP response headers (array of strings)
     */
    public function addSemestreWithHttpInfo($diplome, $accro_m, $accro_p, $semestre = null)
    {
        $returnType = '\Swagger\Client\Model\SemestreBody[]';
        $request = $this->addSemestreRequest($diplome, $accro_m, $accro_p, $semestre);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SemestreBody[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation addSemestreAsync
     *
     * adds a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addSemestreAsync($diplome, $accro_m, $accro_p, $semestre = null)
    {
        return $this->addSemestreAsyncWithHttpInfo($diplome, $accro_m, $accro_p, $semestre)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addSemestreAsyncWithHttpInfo
     *
     * adds a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addSemestreAsyncWithHttpInfo($diplome, $accro_m, $accro_p, $semestre = null)
    {
        $returnType = '\Swagger\Client\Model\SemestreBody[]';
        $request = $this->addSemestreRequest($diplome, $accro_m, $accro_p, $semestre);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addSemestre'
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function addSemestreRequest($diplome, $accro_m, $accro_p, $semestre = null)
    {
        // verify the required parameter 'diplome' is set
        if ($diplome === null || (is_array($diplome) && count($diplome) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $diplome when calling addSemestre'
            );
        }
        // verify the required parameter 'accro_m' is set
        if ($accro_m === null || (is_array($accro_m) && count($accro_m) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_m when calling addSemestre'
            );
        }
        // verify the required parameter 'accro_p' is set
        if ($accro_p === null || (is_array($accro_p) && count($accro_p) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_p when calling addSemestre'
            );
        }

        $resourcePath = '/diplomes/{diplome}/mentions/{accroM}/parcours/{accroP}/semestres';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($diplome !== null) {
            $resourcePath = str_replace(
                '{' . 'diplome' . '}',
                ObjectSerializer::toPathValue($diplome),
                $resourcePath
            );
        }
        // path params
        if ($accro_m !== null) {
            $resourcePath = str_replace(
                '{' . 'accroM' . '}',
                ObjectSerializer::toPathValue($accro_m),
                $resourcePath
            );
        }
        // path params
        if ($accro_p !== null) {
            $resourcePath = str_replace(
                '{' . 'accroP' . '}',
                ObjectSerializer::toPathValue($accro_p),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($semestre)) {
            $_tempBody = $semestre;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteSemestre
     *
     * deletes a Semestre
     *
     * @param  string $diplome diplome (required)
     * @param  string $accro_m accro_m (required)
     * @param  string $accro_p accro_p (required)
     * @param  string $sem sem (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteSemestre($diplome, $accro_m, $accro_p, $sem)
    {
        $this->deleteSemestreWithHttpInfo($diplome, $accro_m, $accro_p, $sem);
    }

    /**
     * Operation deleteSemestreWithHttpInfo
     *
     * deletes a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSemestreWithHttpInfo($diplome, $accro_m, $accro_p, $sem)
    {
        $returnType = '';
        $request = $this->deleteSemestreRequest($diplome, $accro_m, $accro_p, $sem);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteSemestreAsync
     *
     * deletes a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSemestreAsync($diplome, $accro_m, $accro_p, $sem)
    {
        return $this->deleteSemestreAsyncWithHttpInfo($diplome, $accro_m, $accro_p, $sem)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteSemestreAsyncWithHttpInfo
     *
     * deletes a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSemestreAsyncWithHttpInfo($diplome, $accro_m, $accro_p, $sem)
    {
        $returnType = '';
        $request = $this->deleteSemestreRequest($diplome, $accro_m, $accro_p, $sem);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteSemestre'
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteSemestreRequest($diplome, $accro_m, $accro_p, $sem)
    {
        // verify the required parameter 'diplome' is set
        if ($diplome === null || (is_array($diplome) && count($diplome) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $diplome when calling deleteSemestre'
            );
        }
        // verify the required parameter 'accro_m' is set
        if ($accro_m === null || (is_array($accro_m) && count($accro_m) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_m when calling deleteSemestre'
            );
        }
        // verify the required parameter 'accro_p' is set
        if ($accro_p === null || (is_array($accro_p) && count($accro_p) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_p when calling deleteSemestre'
            );
        }
        // verify the required parameter 'sem' is set
        if ($sem === null || (is_array($sem) && count($sem) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sem when calling deleteSemestre'
            );
        }

        $resourcePath = '/diplomes/{diplome}/mentions/{accroM}/parcours/{accroP}/semestres/{sem}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($diplome !== null) {
            $resourcePath = str_replace(
                '{' . 'diplome' . '}',
                ObjectSerializer::toPathValue($diplome),
                $resourcePath
            );
        }
        // path params
        if ($accro_m !== null) {
            $resourcePath = str_replace(
                '{' . 'accroM' . '}',
                ObjectSerializer::toPathValue($accro_m),
                $resourcePath
            );
        }
        // path params
        if ($accro_p !== null) {
            $resourcePath = str_replace(
                '{' . 'accroP' . '}',
                ObjectSerializer::toPathValue($accro_p),
                $resourcePath
            );
        }
        // path params
        if ($sem !== null) {
            $resourcePath = str_replace(
                '{' . 'sem' . '}',
                ObjectSerializer::toPathValue($sem),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSemestre
     *
     * gets a Semestre
     *
     * @param  string $diplome diplome (required)
     * @param  string $accro_m accro_m (required)
     * @param  string $accro_p accro_p (required)
     * @param  string $sem sem (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Semestre
     */
    public function getSemestre($diplome, $accro_m, $accro_p, $sem)
    {
        list($response) = $this->getSemestreWithHttpInfo($diplome, $accro_m, $accro_p, $sem);
        return $response;
    }

    /**
     * Operation getSemestreWithHttpInfo
     *
     * gets a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Semestre, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSemestreWithHttpInfo($diplome, $accro_m, $accro_p, $sem)
    {
        $returnType = '\Swagger\Client\Model\Semestre';
        $request = $this->getSemestreRequest($diplome, $accro_m, $accro_p, $sem);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Semestre',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSemestreAsync
     *
     * gets a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSemestreAsync($diplome, $accro_m, $accro_p, $sem)
    {
        return $this->getSemestreAsyncWithHttpInfo($diplome, $accro_m, $accro_p, $sem)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSemestreAsyncWithHttpInfo
     *
     * gets a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSemestreAsyncWithHttpInfo($diplome, $accro_m, $accro_p, $sem)
    {
        $returnType = '\Swagger\Client\Model\Semestre';
        $request = $this->getSemestreRequest($diplome, $accro_m, $accro_p, $sem);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSemestre'
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSemestreRequest($diplome, $accro_m, $accro_p, $sem)
    {
        // verify the required parameter 'diplome' is set
        if ($diplome === null || (is_array($diplome) && count($diplome) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $diplome when calling getSemestre'
            );
        }
        // verify the required parameter 'accro_m' is set
        if ($accro_m === null || (is_array($accro_m) && count($accro_m) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_m when calling getSemestre'
            );
        }
        // verify the required parameter 'accro_p' is set
        if ($accro_p === null || (is_array($accro_p) && count($accro_p) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_p when calling getSemestre'
            );
        }
        // verify the required parameter 'sem' is set
        if ($sem === null || (is_array($sem) && count($sem) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sem when calling getSemestre'
            );
        }

        $resourcePath = '/diplomes/{diplome}/mentions/{accroM}/parcours/{accroP}/semestres/{sem}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($diplome !== null) {
            $resourcePath = str_replace(
                '{' . 'diplome' . '}',
                ObjectSerializer::toPathValue($diplome),
                $resourcePath
            );
        }
        // path params
        if ($accro_m !== null) {
            $resourcePath = str_replace(
                '{' . 'accroM' . '}',
                ObjectSerializer::toPathValue($accro_m),
                $resourcePath
            );
        }
        // path params
        if ($accro_p !== null) {
            $resourcePath = str_replace(
                '{' . 'accroP' . '}',
                ObjectSerializer::toPathValue($accro_p),
                $resourcePath
            );
        }
        // path params
        if ($sem !== null) {
            $resourcePath = str_replace(
                '{' . 'sem' . '}',
                ObjectSerializer::toPathValue($sem),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSemestres
     *
     * gets Semestres
     *
     * @param  string $diplome diplome (required)
     * @param  string $accro_m accro_m (required)
     * @param  string $accro_p accro_p (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ListSemestres
     */
    public function getSemestres($diplome, $accro_m, $accro_p)
    {
        list($response) = $this->getSemestresWithHttpInfo($diplome, $accro_m, $accro_p);
        return $response;
    }

    /**
     * Operation getSemestresWithHttpInfo
     *
     * gets Semestres
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ListSemestres, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSemestresWithHttpInfo($diplome, $accro_m, $accro_p)
    {
        $returnType = '\Swagger\Client\Model\ListSemestres';
        $request = $this->getSemestresRequest($diplome, $accro_m, $accro_p);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ListSemestres',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSemestresAsync
     *
     * gets Semestres
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSemestresAsync($diplome, $accro_m, $accro_p)
    {
        return $this->getSemestresAsyncWithHttpInfo($diplome, $accro_m, $accro_p)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSemestresAsyncWithHttpInfo
     *
     * gets Semestres
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSemestresAsyncWithHttpInfo($diplome, $accro_m, $accro_p)
    {
        $returnType = '\Swagger\Client\Model\ListSemestres';
        $request = $this->getSemestresRequest($diplome, $accro_m, $accro_p);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSemestres'
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSemestresRequest($diplome, $accro_m, $accro_p)
    {
        // verify the required parameter 'diplome' is set
        if ($diplome === null || (is_array($diplome) && count($diplome) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $diplome when calling getSemestres'
            );
        }
        // verify the required parameter 'accro_m' is set
        if ($accro_m === null || (is_array($accro_m) && count($accro_m) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_m when calling getSemestres'
            );
        }
        // verify the required parameter 'accro_p' is set
        if ($accro_p === null || (is_array($accro_p) && count($accro_p) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_p when calling getSemestres'
            );
        }

        $resourcePath = '/diplomes/{diplome}/mentions/{accroM}/parcours/{accroP}/semestres';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($diplome !== null) {
            $resourcePath = str_replace(
                '{' . 'diplome' . '}',
                ObjectSerializer::toPathValue($diplome),
                $resourcePath
            );
        }
        // path params
        if ($accro_m !== null) {
            $resourcePath = str_replace(
                '{' . 'accroM' . '}',
                ObjectSerializer::toPathValue($accro_m),
                $resourcePath
            );
        }
        // path params
        if ($accro_p !== null) {
            $resourcePath = str_replace(
                '{' . 'accroP' . '}',
                ObjectSerializer::toPathValue($accro_p),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSemestre
     *
     * update a Semestre
     *
     * @param  string $diplome diplome (required)
     * @param  string $accro_m accro_m (required)
     * @param  string $accro_p accro_p (required)
     * @param  string $sem sem (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\SemestreBody
     */
    public function updateSemestre($diplome, $accro_m, $accro_p, $sem, $semestre = null)
    {
        list($response) = $this->updateSemestreWithHttpInfo($diplome, $accro_m, $accro_p, $sem, $semestre);
        return $response;
    }

    /**
     * Operation updateSemestreWithHttpInfo
     *
     * update a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\SemestreBody, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSemestreWithHttpInfo($diplome, $accro_m, $accro_p, $sem, $semestre = null)
    {
        $returnType = '\Swagger\Client\Model\SemestreBody';
        $request = $this->updateSemestreRequest($diplome, $accro_m, $accro_p, $sem, $semestre);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SemestreBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Semestre[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateSemestreAsync
     *
     * update a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSemestreAsync($diplome, $accro_m, $accro_p, $sem, $semestre = null)
    {
        return $this->updateSemestreAsyncWithHttpInfo($diplome, $accro_m, $accro_p, $sem, $semestre)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSemestreAsyncWithHttpInfo
     *
     * update a Semestre
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSemestreAsyncWithHttpInfo($diplome, $accro_m, $accro_p, $sem, $semestre = null)
    {
        $returnType = '\Swagger\Client\Model\SemestreBody';
        $request = $this->updateSemestreRequest($diplome, $accro_m, $accro_p, $sem, $semestre);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSemestre'
     *
     * @param  string $diplome (required)
     * @param  string $accro_m (required)
     * @param  string $accro_p (required)
     * @param  string $sem (required)
     * @param  \Swagger\Client\Model\SemestreBody $semestre Semestre item to add/edit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateSemestreRequest($diplome, $accro_m, $accro_p, $sem, $semestre = null)
    {
        // verify the required parameter 'diplome' is set
        if ($diplome === null || (is_array($diplome) && count($diplome) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $diplome when calling updateSemestre'
            );
        }
        // verify the required parameter 'accro_m' is set
        if ($accro_m === null || (is_array($accro_m) && count($accro_m) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_m when calling updateSemestre'
            );
        }
        // verify the required parameter 'accro_p' is set
        if ($accro_p === null || (is_array($accro_p) && count($accro_p) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accro_p when calling updateSemestre'
            );
        }
        // verify the required parameter 'sem' is set
        if ($sem === null || (is_array($sem) && count($sem) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sem when calling updateSemestre'
            );
        }

        $resourcePath = '/diplomes/{diplome}/mentions/{accroM}/parcours/{accroP}/semestres/{sem}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($diplome !== null) {
            $resourcePath = str_replace(
                '{' . 'diplome' . '}',
                ObjectSerializer::toPathValue($diplome),
                $resourcePath
            );
        }
        // path params
        if ($accro_m !== null) {
            $resourcePath = str_replace(
                '{' . 'accroM' . '}',
                ObjectSerializer::toPathValue($accro_m),
                $resourcePath
            );
        }
        // path params
        if ($accro_p !== null) {
            $resourcePath = str_replace(
                '{' . 'accroP' . '}',
                ObjectSerializer::toPathValue($accro_p),
                $resourcePath
            );
        }
        // path params
        if ($sem !== null) {
            $resourcePath = str_replace(
                '{' . 'sem' . '}',
                ObjectSerializer::toPathValue($sem),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($semestre)) {
            $_tempBody = $semestre;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
