<?php
/**
 * UE
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apogee API
 *
 * API for apogee
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nassima.ziani1996@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * UE Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UE implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UE';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id_ue' => '\Swagger\Client\Model\IdUE',
        'sem' => 'int',
        'nom_ue' => 'string',
        'ects' => 'float',
        'a_choix' => 'bool',
        'seuil' => 'int',
        'list_ecu_es' => '\Swagger\Client\Model\ListECUEs',
        'list_sem' => '\Swagger\Client\Model\ListSemestres',
        'list_parcours' => '\Swagger\Client\Model\ListParcours'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id_ue' => null,
        'sem' => null,
        'nom_ue' => null,
        'ects' => 'float',
        'a_choix' => null,
        'seuil' => null,
        'list_ecu_es' => null,
        'list_sem' => null,
        'list_parcours' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_ue' => 'idUE',
        'sem' => 'sem',
        'nom_ue' => 'nomUE',
        'ects' => 'ECTS',
        'a_choix' => 'AChoix',
        'seuil' => 'seuil',
        'list_ecu_es' => 'listECUEs',
        'list_sem' => 'listSem',
        'list_parcours' => 'listParcours'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_ue' => 'setIdUe',
        'sem' => 'setSem',
        'nom_ue' => 'setNomUe',
        'ects' => 'setEcts',
        'a_choix' => 'setAChoix',
        'seuil' => 'setSeuil',
        'list_ecu_es' => 'setListEcuEs',
        'list_sem' => 'setListSem',
        'list_parcours' => 'setListParcours'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_ue' => 'getIdUe',
        'sem' => 'getSem',
        'nom_ue' => 'getNomUe',
        'ects' => 'getEcts',
        'a_choix' => 'getAChoix',
        'seuil' => 'getSeuil',
        'list_ecu_es' => 'getListEcuEs',
        'list_sem' => 'getListSem',
        'list_parcours' => 'getListParcours'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_ue'] = isset($data['id_ue']) ? $data['id_ue'] : null;
        $this->container['sem'] = isset($data['sem']) ? $data['sem'] : null;
        $this->container['nom_ue'] = isset($data['nom_ue']) ? $data['nom_ue'] : null;
        $this->container['ects'] = isset($data['ects']) ? $data['ects'] : null;
        $this->container['a_choix'] = isset($data['a_choix']) ? $data['a_choix'] : null;
        $this->container['seuil'] = isset($data['seuil']) ? $data['seuil'] : null;
        $this->container['list_ecu_es'] = isset($data['list_ecu_es']) ? $data['list_ecu_es'] : null;
        $this->container['list_sem'] = isset($data['list_sem']) ? $data['list_sem'] : null;
        $this->container['list_parcours'] = isset($data['list_parcours']) ? $data['list_parcours'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_ue
     *
     * @return \Swagger\Client\Model\IdUE
     */
    public function getIdUe()
    {
        return $this->container['id_ue'];
    }

    /**
     * Sets id_ue
     *
     * @param \Swagger\Client\Model\IdUE $id_ue id_ue
     *
     * @return $this
     */
    public function setIdUe($id_ue)
    {
        $this->container['id_ue'] = $id_ue;

        return $this;
    }

    /**
     * Gets sem
     *
     * @return int
     */
    public function getSem()
    {
        return $this->container['sem'];
    }

    /**
     * Sets sem
     *
     * @param int $sem sem
     *
     * @return $this
     */
    public function setSem($sem)
    {
        $this->container['sem'] = $sem;

        return $this;
    }

    /**
     * Gets nom_ue
     *
     * @return string
     */
    public function getNomUe()
    {
        return $this->container['nom_ue'];
    }

    /**
     * Sets nom_ue
     *
     * @param string $nom_ue nom_ue
     *
     * @return $this
     */
    public function setNomUe($nom_ue)
    {
        $this->container['nom_ue'] = $nom_ue;

        return $this;
    }

    /**
     * Gets ects
     *
     * @return float
     */
    public function getEcts()
    {
        return $this->container['ects'];
    }

    /**
     * Sets ects
     *
     * @param float $ects ects
     *
     * @return $this
     */
    public function setEcts($ects)
    {
        $this->container['ects'] = $ects;

        return $this;
    }

    /**
     * Gets a_choix
     *
     * @return bool
     */
    public function getAChoix()
    {
        return $this->container['a_choix'];
    }

    /**
     * Sets a_choix
     *
     * @param bool $a_choix a_choix
     *
     * @return $this
     */
    public function setAChoix($a_choix)
    {
        $this->container['a_choix'] = $a_choix;

        return $this;
    }

    /**
     * Gets seuil
     *
     * @return int
     */
    public function getSeuil()
    {
        return $this->container['seuil'];
    }

    /**
     * Sets seuil
     *
     * @param int $seuil seuil
     *
     * @return $this
     */
    public function setSeuil($seuil)
    {
        $this->container['seuil'] = $seuil;

        return $this;
    }

    /**
     * Gets list_ecu_es
     *
     * @return \Swagger\Client\Model\ListECUEs
     */
    public function getListEcuEs()
    {
        return $this->container['list_ecu_es'];
    }

    /**
     * Sets list_ecu_es
     *
     * @param \Swagger\Client\Model\ListECUEs $list_ecu_es list_ecu_es
     *
     * @return $this
     */
    public function setListEcuEs($list_ecu_es)
    {
        $this->container['list_ecu_es'] = $list_ecu_es;

        return $this;
    }

    /**
     * Gets list_sem
     *
     * @return \Swagger\Client\Model\ListSemestres
     */
    public function getListSem()
    {
        return $this->container['list_sem'];
    }

    /**
     * Sets list_sem
     *
     * @param \Swagger\Client\Model\ListSemestres $list_sem list_sem
     *
     * @return $this
     */
    public function setListSem($list_sem)
    {
        $this->container['list_sem'] = $list_sem;

        return $this;
    }

    /**
     * Gets list_parcours
     *
     * @return \Swagger\Client\Model\ListParcours
     */
    public function getListParcours()
    {
        return $this->container['list_parcours'];
    }

    /**
     * Sets list_parcours
     *
     * @param \Swagger\Client\Model\ListParcours $list_parcours list_parcours
     *
     * @return $this
     */
    public function setListParcours($list_parcours)
    {
        $this->container['list_parcours'] = $list_parcours;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


