<?php
/**
 * ECUEBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apogee API
 *
 * API for apogee
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nassima.ziani1996@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ECUEBodyTest Class Doc Comment
 *
 * @category    Class
 * @description ECUEBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ECUEBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ECUEBody"
     */
    public function testECUEBody()
    {
    }

    /**
     * Test attribute "sem"
     */
    public function testPropertySem()
    {
    }

    /**
     * Test attribute "nom_ecue"
     */
    public function testPropertyNomEcue()
    {
    }

    /**
     * Test attribute "cnu"
     */
    public function testPropertyCnu()
    {
    }

    /**
     * Test attribute "ects"
     */
    public function testPropertyEcts()
    {
    }

    /**
     * Test attribute "cm"
     */
    public function testPropertyCm()
    {
    }

    /**
     * Test attribute "td"
     */
    public function testPropertyTd()
    {
    }

    /**
     * Test attribute "tp"
     */
    public function testPropertyTp()
    {
    }

    /**
     * Test attribute "dist"
     */
    public function testPropertyDist()
    {
    }

    /**
     * Test attribute "gpcm"
     */
    public function testPropertyGpcm()
    {
    }

    /**
     * Test attribute "gptd"
     */
    public function testPropertyGptd()
    {
    }

    /**
     * Test attribute "gptp"
     */
    public function testPropertyGptp()
    {
    }

    /**
     * Test attribute "ccec"
     */
    public function testPropertyCcec()
    {
    }

    /**
     * Test attribute "ccor"
     */
    public function testPropertyCcor()
    {
    }

    /**
     * Test attribute "cctp"
     */
    public function testPropertyCctp()
    {
    }

    /**
     * Test attribute "ccnb"
     */
    public function testPropertyCcnb()
    {
    }

    /**
     * Test attribute "exec"
     */
    public function testPropertyExec()
    {
    }

    /**
     * Test attribute "exor"
     */
    public function testPropertyExor()
    {
    }

    /**
     * Test attribute "extp"
     */
    public function testPropertyExtp()
    {
    }

    /**
     * Test attribute "cciec"
     */
    public function testPropertyCciec()
    {
    }

    /**
     * Test attribute "ccior"
     */
    public function testPropertyCcior()
    {
    }

    /**
     * Test attribute "ccitp"
     */
    public function testPropertyCcitp()
    {
    }

    /**
     * Test attribute "ccinb"
     */
    public function testPropertyCcinb()
    {
    }

    /**
     * Test attribute "deec"
     */
    public function testPropertyDeec()
    {
    }

    /**
     * Test attribute "deor"
     */
    public function testPropertyDeor()
    {
    }

    /**
     * Test attribute "detp"
     */
    public function testPropertyDetp()
    {
    }

    /**
     * Test attribute "s2ec"
     */
    public function testPropertyS2ec()
    {
    }

    /**
     * Test attribute "s2or"
     */
    public function testPropertyS2or()
    {
    }

    /**
     * Test attribute "s2tp"
     */
    public function testPropertyS2tp()
    {
    }
}
