<?php
/**
 * MentionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apogee API
 *
 * API for apogee
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nassima.ziani1996@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MentionTest Class Doc Comment
 *
 * @category    Class
 * @description Mention
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MentionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Mention"
     */
    public function testMention()
    {
    }

    /**
     * Test attribute "id_m"
     */
    public function testPropertyIdM()
    {
    }

    /**
     * Test attribute "nom_m"
     */
    public function testPropertyNomM()
    {
    }

    /**
     * Test attribute "accro_m"
     */
    public function testPropertyAccroM()
    {
    }

    /**
     * Test attribute "diplome"
     */
    public function testPropertyDiplome()
    {
    }

    /**
     * Test attribute "list_parcours"
     */
    public function testPropertyListParcours()
    {
    }
}
