<?php
/**
 * MentionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apogee API
 *
 * API for apogee
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nassima.ziani1996@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MentionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MentionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addMention
     *
     * adds a Mention.
     *
     */
    public function testAddMention()
    {
    }

    /**
     * Test case for deleteMention
     *
     * deletes a Mention.
     *
     */
    public function testDeleteMention()
    {
    }

    /**
     * Test case for getMentionAccro
     *
     * gets a Mention by it's accro.
     *
     */
    public function testGetMentionAccro()
    {
    }

    /**
     * Test case for getMentions
     *
     * gets Mentions.
     *
     */
    public function testGetMentions()
    {
    }

    /**
     * Test case for updateMentionAccro
     *
     * update a Mention by its accro.
     *
     */
    public function testUpdateMentionAccro()
    {
    }
}
